### ISSUE TITLE
New ansi version

### ISSUE THREAD

**Issue by cschramm** [busyloop/powerbar#12]
ansi 1.5.0 was released and fixes a warning in Ruby 2.2. The dependency should be relaxed to ~> 1.4 I think.

**Comment by m-o-e** [comment]
Thanks for the heads up!

**Comment by m-o-e** [comment]
Fixed in 03fa2207d924869cdd2ba8c1440ebbda1f832866 and pushed [v1.0.2](https://rubygems.org/gems/powerbar/versions/1.0.12)
